/* 
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
*/

//solution
const answer = (limit: number): number => {
    //create a total accumulator, previous, current
    let total: number = 2, previous: number = 1, current: number = 2

    //run fibonacci sequence until 4 million
    while ((previous + current) < limit) {
        
        let sum = previous + current
    
        //each answer in fibonacci is checked to see if it's even and add total if true
        if (sum % 2 == 0) {
            total = total + sum
        }

        previous = current
        current = sum
    }

    return total
}

console.log(answer(4000000))

export {}